### ISSUE TITLE
Correctly formatted data

### ISSUE THREAD

**Issue by kstats** [liuyuemaicha/Adversarial-Learning-for-Neural-Dialogue-Generation-in-Tensorflow#1]
Hello!

I'm trying to run this repo, and am running into problems with the data.  Can you please share how to obtain and format the data?  What was the source?

Thank you!

**Comment by joemzhao** [comment]
Hi,

I am not the author of this repo but I guess the author used the pickle file in:
https://github.com/luchi007/RNN_Text_Classify

I am also implementing this topic and I found this from the author's blog (unfortunately in Chinese) where __RNN_Text_Classify__  is referenced. Hope this helps. 

j

**Comment by kstats** [comment]
I'm more interested in if this format aligns with the dialogue data produced with the original paper's code (available here: https://github.com/jiweil/Neural-Dialogue-Generation).

That repository takes the past two utterances in as input to the gen/disc models, and I'm wondering if this repository is set up to do the same.

**Comment by joemzhao** [comment]
I guess the data formats are not aligned. Hence we have to make some modifications accordingly.

**Comment by brightmart** [comment]
1.only need following data under train_data. each line is a a answer(or query)
'chitchat.train.answer','chitchat.train.query','chitchat.dev.answer','chitchat.dev.query','chitchat.test.answer'.'chitchat.test.query'

2.data/subj0.pkl:https: 
find it http://github.com/luchi007/RNN_Text_Classify/tree/master/data

**Comment by liuyuemaicha** [comment]
sorry, the Correctly formatted data  of every train_files like this  -- one row , one sentence: 

you ' r e a bad girl and a false sister and i have done with you
i ' m not talking about the furs or the silverware
let ' s see you carry her down the hill my boy
perhaps it was just an accident as he claimed at the time
oh what ' s the use porter ?
my father demanded that i say it today in front of everyone
oh you can tell them he is better than good
i ' m usually a very calm and collected person
you ' r e partly right but only partly
all my black shit on black leather big ass medallion and shit on like this
man you ain ' t got no credentials
whatever it is you wish to tell me tell me without any hesitation
then why did you go to work for her ?

**Comment by liuyuemaicha** [comment]
I have added the training data (only for examples)
