### ISSUE TITLE
您好，请问al_train运行之后怎么评价模型是变好了还是变坏了？我看后边没有perplexity了，我用gan训练之后效果比seq2seq反而降低了，大概需要训练多久呢？

### ISSUE THREAD

**Issue by zzzzxciid** [liuyuemaicha/Adversarial-Learning-for-Neural-Dialogue-Generation-in-Tensorflow#5]

**Comment by liuyuemaicha** [comment]
我是看D的loss值（accuracy）和G 的loss值。还有在最后的模型手动测试对比。您说的perplexity，在之前的实验中也有用到，但当时感觉和G的loss值差不多，perplexity降低了也不能体现聊天模型就一定会更好。所以我就没用。不过可以加上试试。谢谢您的提醒。gan训练模型时，G的预训练要把握好，一般预训练到能做 一般回复就好。al_train的训练过程中，Dloss值一般是趋于下降，而G的loss值先稍微上扬，在逐渐下降，不知道你训练中是否这样……
